# DataFrames I

In [3]:
import pandas as pd

## Methods and Attributes between Series and DataFrames
- A `DataFrame` is a 2-dimensional table consisting of rows and columns.
- Like with a `Series`, Pandas assigns an index position/label to each `DataFrame` row.
- Pandas uses a `NaN` designation for cells that have a missing value.
- The `pd.read_csv` function imports a `DataFrame` by default.
- The `nba.csv` dataset is a collection of basketball players.
- The last row in the dataset is completely empty.

In [5]:
nba = pd.read_csv("nba.csv")

- The `DataFrame` and `Series` have common and exclusive methods/attributes.
- Some methods/attributes will return different types of data.

- The `head` method returns rows from the start of the `DataFrame`.
- The `tail` method returns rows from the end of the `DataFrame`.

In [6]:
nba.head()

,Name,Team,Position,Height,Weight,College,Salary
0,Asa Newell,Atlanta Hawks,F,6-10,220.0,Georgia,4000000.0
1,Buddy Hield,Atlanta Hawks,G-F,6-4,220.0,Oklahoma,9700000.0
2,C.J. McCollum,Atlanta Hawks,G,6-3,190.0,Lehigh,30700000.0
3,Caleb Houstan,Atlanta Hawks,F,6-8,205.0,Michigan,1300000.0
4,Christian Koloko,Atlanta Hawks,C,7-0,230.0,Arizona,NaN

In [9]:
nba.tail(n=9)

,Name,Team,Position,Height,Weight,College,Salary
518,Justin Champagnie,Washington Wizards,F,6-6,206.0,Pittsburgh,2700000.0
519,Kyshawn George,Washington Wizards,G-F,6-8,205.0,Miami (FL),3800000.0
520,Leaky Black,Washington Wizards,F,6-9,218.0,North Carolina,600000.0
521,Sharife Cooper,Washington Wizards,G,6-1,180.0,Auburn,NaN
522,Trae Young,Washington Wizards,G,6-1,164.0,Oklahoma,47500000.0
523,Tre Johnson,Washington Wizards,G,6-5,190.0,Texas,9400000.0
524,Tristan Vukcevic,Washington Wizards,C,6-11,220.0,NaN,3000000.0
525,Will Riley,Washington Wizards,G-F,6-8,186.0,Illinois,4300000.0
526,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- The `index` attribute stores the object that holds the index labels.

In [10]:
nba.index

RangeIndex(start=0, stop=527, step=1)

- The `shape` attribute is a tuple with the dimensions (height x width) of the data structure.

In [11]:
nba.shape

(527, 7)

- The `dtypes` attribute holds the data types.
- The `DataFrame` has multiple columns, so Pandas creates a `Series` where the index labels are the column names and the values are their data types.

In [12]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

- The `hasnans` attribute returns `True` if a `Series` contains any missing values.
- The attribute does not exist on a `DataFrame`.

- The `columns` attribute returns the column labels of a `DataFrame`.
- The attribute does not exist on a `Series`.

In [16]:
nba.iterrows()

- The `axes` attribute returns a list of the axis indexes.
- The `Series` has only one index, so the list has 1 entry.
- The `DataFrame` has two indexes (rows and columns), so the list has 2 entries.

In [17]:
nba.axes

[RangeIndex(start=0, stop=527, step=1),
 Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='str')]

- The `info` method returns a summary of the pandas object.
- The output includes the index type, a count of non-null values, the data types, and the memory usage.

In [18]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 527 entries, 0 to 526
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      526 non-null    str
 1   Team      526 non-null    str
 2   Position  526 non-null    str
 3   Height    526 non-null    str
 4   Weight    526 non-null    float64
 5   College   485 non-null    str
 6   Salary    474 non-null    float64
dtypes: float64(2), str(5)
memory usage: 28.9 KB

- The `info` method on a `DataFrame` outputs the details _per_ column.

## Differences between Shared Methods
- The same method may work differently on a `Series` vs. a `DataFrame`.

In [24]:
s = pd.Series([1,2,3,4,5])
revenue = pd.read_csv("revenue.csv",index_col="Date")
print(revenue)

         New York  Los Angeles  Miami
Date
1/1/26        985          122    499
1/2/26        738          788    534
1/3/26         14           20    933
1/4/26        730          904    885
1/5/26        114           71    253
1/6/26        936          502    497
1/7/26        123          996    115
1/8/26        935          492    886
1/9/26        846          954    823
1/10/26        54          285    216

- The `sum` method adds a `Series`'s values. There is only one direction to add.

In [27]:
s.sum()

np.int64(15)

In [39]:
print("",revenue.sum(axis="columns").sum())
# print("All Columns",revenue.sum(axis=0))
# print("Index Rows",revenue.sum(axis="index"))
print("All Rows",revenue.sum(axis=1).sum())

 16250
All Rows 16250

- On a `DataFrame`, the `sum` method defaults to adding the column values.
- The method returns a `Series` where the index labels are the column names and the values are the sum totals.
- The `axis` parameter customizes the direction that we add across. Pass `"index"` or `0` to add values by traversing the rows.

In [48]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

frames = [df1, df2, df3]
result = pd.concat(frames)
print(result)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

- Pass the `axis` parameter an argument of `"columns"` to calculate the sum of each row's values.
- We are traversing the "columns" in calculating the sum rather than traversing the "index".

- Now that we have a `Series` of numbers, we can also calculate total business revenue by invoking `sum`.

## Select One Column from a DataFrame

In [41]:
type(nba.Team)

pandas.Series

- Pandas will define a `DataFrame` attribute for each column name.
- Use attribute syntax (`df.column_name`) to select a column.
- Pandas extracts the `DataFrame` column as a `Series`.

- Case-sensitivity matters. Write out the column name with correct capitalization.
- The attribute accesssyntax will not work if the column name has spaces.

- The extracted column is a valid `Series` with all of its regular methods.
- The `value_counts` counts the number of times that each distinct value occurs.

- Square bracket syntax also extracts a column (`df["column name"]`).
- The syntax will not work if the column name has spaces or special symbols.

- Recall Pandas 3's **Copy-on-Write** principles.
- Extracting a column returns an object that behaves as a copy.
- The underlying data is still shared between `Series` and `DataFrame`.
- When we perform a mutative operation on the `Series`, Pandas will create a copy of the underlying data.
- In summary, mutating the extracted `Series` will **not** mutate the original `DataFrame`.

## Select Multiple Columns from a DataFrame
- Use square brackets with a list of column names to extract multiple `DataFrame` columns.
- Pandas stores the result in a new `DataFrame` that behaves like a copy.

- The order of list elements impacts the order of the `DataFrame`'s columns.

- Assign the list to a variable for an easier syntax.

## Add New Column to DataFrame
- Use square bracket extraction syntax with an equal sign to add a new `Series` to a `DataFrame`.
- Be careful here. If you reference an existing column, Pandas will overwrite it.

- The `insert` method adds an column at a specific column index.
- The `insert` method mutates the existing `DataFrame`. It does not return a value.
- The column index starts counting from 0. The `Name` column is index 0.
- `loc=3` means the new columns becomes the 4th column (after `Position`).

- The right-hand side of the equal sign can also be a `Series`.
- Let's imagine a scenario where each player's salary doubled.

- Here's another example with subtraction.

## Create Columns with the assign Method
- The `assign` method returns a new `DataFrame`  with one or more new columns.
- The method differs from direct assignment (`df["col"] = value`), which **mutates** the original `DataFrame`.

- Pass keyword arguments where the parameter is the new column name and the value is a `Series`.

## Drop Rows with Missing Values
- Pandas designates missing values with a `NaN`.

- The `dropna` method deletes rows with missing values.
- The method's default behavior is to remove a row if it contains *any* missing values.

- Pass the `how` parameter an argument of "all" to remove rows where all the values are `NaN`.
- This solution effectively removes the final `DataFrame` rows which holds only missing values.

- The `subset` parameter limits the columns that pandas will use to drop rows with missing values.
- The next example drop rows with a missing value in either the `College` or `Salary` column (or both).

- The `thresh` parameter keeps rows with a minimum number of present values.
- `thresh` is useful when some missing data is acceptable and you want to drop rows that are *mostly* empty.
- The next example passes an argument of 5, which keeps rows with at least 5 non-null values (out of 7 columns).

## Fill in Missing Values with the fillna Method
- The `fillna` method replaces missing `NaN` values with its argument.
- The `fillna` method is available on both `DataFrame` and `Series` objects.
- The `fillna` method returns a new object with missing values replaced.  The original is not mutated.

- Pass `fillna` a **dictionary** to specify replacement values _per_ column.
- The dictionary keys will be the column names, and the dictionary values are the replacement values.

- The next example replaces `NaN` values with 0 in the `Salary` column.

## Fill Missing Values with a Forward Fill or Back Fill
- Forward fills and backward fills are two alternate stategies for replacing missing values.
- Fills are ideal when the previous or next observation is a reasonable estimate for a missing value.
- The `temperatures.csv` file has missing values in the `High Temp` column.
- Example: When measuring temperatures, it's reasonable to guess that a day's temperature will be similar to the one on the previous or next day.

- The `ffill` method **forward-fills** missing values.
- Pandas replaces each `NaN` with the last valid value above it.
- For example, index 2's value of 33.0 replaces index 3's missing `NaN` value.

- The `bfill` method **backward-fills** missing values.
- Pandas replaces each `NaN` with the next valid value below it.
- For example, index 4's value of 38.0 replaces index 3's missing `NaN` value.

- The `limit` parameter places a boundary on how many consecutive `NaN` values to fill.
- The values at row indexes 9, 10, and 11 are all `NaN`.
- An argument of 1 replaces 1 `NaN` value in the sequence (index 9) while keeping the other `NaN`s (index 10, 11).

## Convert Data Types with the astype Method I
- The `astype` method converts a `Series's` values to a specified type.
- Developers sometimes use the word "cast" to describe type conversion (i.e., "we cast this number from int to float').
- Pandas cannot convert `NaN` values to numeric types, so we need to eliminate/replace them before we perform the conversion.

- Pass in the specified type as either a string or the core Python data type.
- The `dtypes` attribute returns a `Series` with the `DataFrame`'s columns and their types.

- We can then use the assignment operator (`=`) to replace the column.

- The second option is to invoke `astype` on the `DataFrame` and pass in a dictionary.
- The keys should be the column names, and the values should be the desired data types.

- A 64-bit integer (`int64`) can represent values from -9,223,372,036,854,775,808 (quadrillion) to 9,223,372,036,854,775,807.
- A 32-bit integer (`int32`) can represent values from -2,147,483,648 to 2,147,483,647.
- A 16-bit integer (`int16`) can represent values from -32,768 to 32,767.
- A 32-bit integer should be large enough to model every salary in the dataset.
- The `memory_usage` method returns the amount of bytes that each columnn's data occupies in memory.

- Pass the `astype` method an instance of a data type at the top-level of pandas.

- The data type will update from `int64` to `Int32`.
- Notice the difference in casing. The two are actually different types from different libraries.
- `int64` comes from `numpy` and `Int32` comes from Pandas.
- The Pandas integers support missing values, while the NumPy integers do not support them.

## Convert to Numbers with the to_numeric Function
- The `pd.to_numeric` function converts values to a numeric type (`int` or `float`).

- The `astype` method will fail if Pandas cannot convert a value to the specified type.

- The `pd.to_numeric` function attempts to convert to a numeric data type (integer or float)
- The `errors` parameter sets what happens when Pandas cannot convert a value.
- An argument of `raise` (the default) raises an exception on failure.
- An argument of `coerce` converts failures to `NaN`.

## Select Columns by Type with the select_dtypes Method
- The `select_dtypes` method targets columns by their data types.
- The `include` and `exclude` parameters both accept data types as strings.
- The `include` parameter keeps the columns matching the specified type(s) (e.g., `"number"`, `"str"`, `"category"`).
- The `exclude` parameter drops columns matching the specified type.

- The next example targets all numeric columns (integers and floats).

- The next example targets string columns

## Convert Data Types with the astype Method II: Categories
- The `category` type is ideal for columns with a limited number of unique values.
- For categories, pandas does not create a separate copy of every string/cell in memory. 
- Rather, Pandas connects each distinct string to a numeric representation. Integers are cheaper to store in memory than strings.

- The `nunique` method returns a count of the number of unique values per column.

- The `Position` and `Team` columns are good candidates to be category columns.
- There are 7 unique positions and 30 unique teams in a DataFrame with ~600 rows.

- Converting to `category` reduces memory usage.

- We've reduced the memory by nearly a third!

## Attribute Namespaces
- Pandas nests related methods underneath attributes/namespaces.

- For example, the `str` attribute holds string methods.

- The `cat` namespace holds methods for categorical columns.
- The `cat.categories` attribute returns the distinct categories for a categorical column.

## Sort a DataFrame with the sort_values Method I
- The `sort_values` method sorts a `DataFrame` by the values in one or more columns.
- If sorting by a single column, pass a string with its name.
- The default sort order is ascending (alphabetical for strings).
- The first parameter (`by`) expects the column(s) to sort by.
- The `ascending` parameter customizes the sort order.
- The `na_position` parameter customizes where pandas places `NaN` values.

## Sort a DataFrame with the sort_values Method II: Multiple Columns
- To sort by multiple columns, pass the `by` parameter a list of column names. Pandas will sort in the specified column order (first to last).
- Pass the `ascending` parameter a Boolean to sort all columns in a consistent order (all ascending or all descending).
- Pass `ascending` a list to customize the sort order *per* column. The `ascending` list length must match the `by` list.

## Sort with Ordered Categories
- By default, category values have no ranking.

- The `nunique` methods returns a count of unique values.
- The `unique` method returns a list of all distinct/unique values.

- An **ordered** categorical assigns a rank to the sequence (e.g., "Standard" < "Deluxe" < "Suite" < "Presidential").
- We'll create a `CategoricalDtype` instance with an ordered list of categories.
- "Standard" comes before "Deluxe", which comes before "Suite".

- The `sort_values` method will use category order, not alphabetical order.

## Sort a DataFrame by its Index
- The `sort_index` method sorts the `DataFrame` by its index positions/labels.
- Assign back to the original variable to overwrite the old `DataFrame`.

## Rank Values with the rank Method
- The `rank` method assigns a numeric ranking to each `Series` value.
- Pandas will assign the same rank to equal values and create a "gap" in the dataset for the ranks.

- The `method` parameter controls how Pandas assigns a rank when multiple values tie for the same rank.

- The `"average"` value (default) uses the average of the rankings.

- The `"min"` value assigns all tied values the lowest rank.

- The `"max"` value assigns all tied values the highest rank.

- The `"dense"` value operates like `"min"` but has gaps in the ranking.
- The values of 90 and 90 tie for a rank of 2.
- The value of 100 is assigned a rank fo 3 instead of 4.

- The `"first"` value breaks up ties based on the number's position.
- The first occurrence of the duplicate (90) in the `Series` gets the smaller rank.