# Assignments: Cleaning Data

## 1. Data in Python Request

* Read in data from the Excel spreadsheet (Alarm Survey Data.xlsx) and put into a Pandas DataFrame
* Check the data type of each column
* Convert object columns into numeric or datetime columns, as needed

In [1]:
from math import isnan

import pandas as pd
import numpy as np

In [10]:
happiness = pd.read_csv("../Data/happiness_survey_data.csv")

In [13]:
happiness

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

## 2. Missing Data Check

* Find any missing data
* Deal with the missing data

In [16]:
happiness.info()

<class 'pandas.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   country_name                      2089 non-null   str
 1   year                              2089 non-null   int64
 2   happiness_score                   2089 non-null   float64
 3   social_support                    2076 non-null   float64
 4   freedom_to_make_life_choices      2057 non-null   float64
 5   healthy_life_expectancy_at_birth  2031 non-null   float64
dtypes: float64(4), int64(1), str(1)
memory usage: 98.1 KB

In [31]:

happiness[happiness["freedom_to_make_life_choices"].isna() == True]

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
30,Algeria,2014,6.354898,0.818189,NaN,65.900002
31,Algeria,2016,5.340854,0.748588,NaN,66.099998
120,Bahrain,2014,6.165134,NaN,NaN,65.959999
278,Cambodia,2006,3.568745,0.793081,NaN,57.639999
361,China,2006,4.560495,0.747011,NaN,65.660004
362,China,2007,4.862862,0.810852,NaN,65.919998
369,China,2014,5.195619,0.820366,NaN,67.739998
370,China,2015,5.303878,0.793734,NaN,68.000000
371,China,2016,5.324956,0.741703,NaN,68.125000
531,Egypt,2008,4.631741,0.738364,NaN,61.580002
834,Iraq,2013,4.725017,0.728285,NaN,60.840000
923,Jordan,2005,6.294660,0.920013,NaN,65.800003
925,Jordan,2008,4.930058,0.766224,NaN,66.339996
972,Kosovo,2008,5.521660,0.883843,NaN,NaN
992,Kuwait,2014,6.180139,NaN,NaN,70.000000
1017,Laos,2012,4.876085,0.692628,NaN,58.160000
1100,Madagascar,2006,3.979751,0.711135,NaN,54.139999
1528,Qatar,2010,6.849653,NaN,NaN,64.699997
1531,Qatar,2015,6.374529,NaN,NaN,66.400002
1575,Saudi Arabia,2005,7.079644,0.867819,NaN,61.200001
1815,Tajikistan,2018,5.497469,0.875243,NaN,61.849998
1816,Tajikistan,2019,5.464015,0.879823,NaN,62.000000
1817,Tajikistan,2020,5.373399,0.789745,NaN,62.150002
1818,Tajikistan,2021,5.286824,0.882889,NaN,62.299999
1895,Turkmenistan,2009,6.567713,0.923846,NaN,59.779999
1896,Turkmenistan,2011,5.791755,0.964419,NaN,60.419998
1943,United Arab Emirates,2014,6.539855,NaN,NaN,65.339996
2001,Uzbekistan,2009,5.260721,0.904678,NaN,62.060001
2002,Uzbekistan,2010,5.095342,0.903226,NaN,62.299999
2038,Vietnam,2014,5.084923,0.792168,NaN,64.820000
2039,Vietnam,2015,5.076315,0.848677,NaN,64.900002
2041,Vietnam,2017,5.175279,NaN,NaN,65.099998

In [27]:
happiness

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

## 3. Inconsistent Text & Typos Check

* Find any inconsistent text and typos
* Deal with the inconsistent text and typos

## 4. Duplicate Data Check

* Find any duplicate data
* Deal with the duplicate data

## 5. Outliers Check

* Find any outliers
* Deal with the outliers

## 6. Data Issues Check

* Quickly explore the updated DataFrame. How do things look now after handling the data issues compared to the original DataFrame?

## 7. Create Columns From Numeric Data

* Read data into Python
* Check the data type of each column
* Create a numeric column using arithmetic
* Create a numeric column using conditional logic

In [ ]:
# Create a “Total Spend” column that includes both the pen cost and shipping cost for each sale
# Create a “Free Shipping” column that says yes if the sale included free shipping, and no otherwise

## 8. Create Columns From DateTime Data

* Calculate the difference between two datetime columns and save it as a new column
* Take the average of a column

In [ ]:
# Calculate the number of days between the purchase and delivery date for each sale
# Save it as a new column called “Delivery Time”
# What were the average days from purchase to delivery?

## 9. Create Columns From Text Data

* Split one column into multiple columns
* Create a Boolean column (True / False) to show whether a text field contains particular words

In [ ]:
# Split the reviews on the “|” character to create two new columns: “User Name” and “Review Text”
# Create a “Leak or Spill” column that flags the reviews that mention either “leak” or “spill”