In [2]:
import pandas as pd

In [3]:
guitars_dict = {
    "Fender Telecaster": "Baby Blue",
    "Gibson Les Paul": "Sunburst",
    "ESP Eclipse": "Dark Green"
}

In [4]:
guitars = pd.Series(guitars_dict)

In [5]:
fender_color = guitars.iat[0]

In [6]:
fender_color

'Baby Blue'

In [7]:
gibson_color = guitars.at["Gibson Les Paul"]

In [8]:
gibson_color

'Sunburst'

In [9]:
esp_color = guitars.loc["ESP Eclipse"]

In [10]:
esp_color

'Dark Green'

In [13]:
pd.read_csv("Incomplete/hot_dogs.csv",usecols=["Winner"]).squeeze("columns")

0          Joey Chestnut
1     Patrick Bertoletti
2          Joey Chestnut
3          Joey Chestnut
4          Joey Chestnut
5          Joey Chestnut
6          Joey Chestnut
7          Joey Chestnut
8          Joey Chestnut
9          Joey Chestnut
10           Matt Stonie
11         Joey Chestnut
12         Joey Chestnut
13         Joey Chestnut
14         Joey Chestnut
15         Joey Chestnut
16         Joey Chestnut
17         Joey Chestnut
18         Joey Chestnut
19      Takeru Kobayashi
20      Takeru Kobayashi
21      Takeru Kobayashi
22      Takeru Kobayashi
23      Takeru Kobayashi
24      Takeru Kobayashi
25         Kazutoyo Arai
26          Steve Keiner
27     Hirofumi Nakajima
28     Hirofumi Nakajima
29     Hirofumi Nakajima
30            Ed Krachie
31            Ed Krachie
32           Mike DeVito
33           Mike DeVito
34           Mike DeVito
35     Frankie Dellarosa
36     Frankie Dellarosa
37           Mike DeVito
38             Jay Green
39             Jay Green
40           Don Wolfman
41           Mark Heller
42      Hiroaki Tominaga
43       Oscar Rodriguez
44         Birgit Felden
45            Emil Gomez
46         Steven Abrams
47        Thomas DeBerry
48           Joe Baldini
49           Jim Mattner
50      Manel Hollenback
51          Lonnie Brown
52        Roberto Muriel
53         John Connolly
54               Unknown
55               Unknown
56       Melody Andorfer
57       Jason Schechter
58           Walter Paul
Name: Winner, dtype: str

In [29]:
people = pd.read_csv("Incomplete/hot_dogs.csv",index_col=["Winner"]).squeeze("columns")
people.index.value_counts().sort_values(ascending=False).tail().is_unique

False

In [6]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
)

frames = [df1, df2, df3]

result = pd.concat(frames)

result.reset_index(drop=True)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [7]:
df1 = pd.DataFrame(
    [
        [24.3, 75.7, "high"],
        [31, 87.8, "high"],
        [22, 71.6, "medium"],
        [35, 95, "medium"],
    ],
    columns=["temp_celsius", "temp_fahrenheit", "windspeed"],
    index=pd.date_range(start="2014-02-12", end="2014-02-15", freq="D"),
)

In [8]:
df1

            temp_celsius  temp_fahrenheit windspeed
2014-02-12          24.3             75.7      high
2014-02-13          31.0             87.8      high
2014-02-14          22.0             71.6    medium
2014-02-15          35.0             95.0    medium

In [15]:
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
print(df)
for x in df:
    print(x)

   A  B
0  1  4
1  2  5
2  3  6
A
B